txt_firstName = "//input[@name='firstName']"
txt_middleName = "//input[@name='middleName']"
txt_lastName = "//input[@name='lastName']"
txt_employee_id = "//div[contains(@class,'oxd-grid-2 orangehrm-full-width-grid')]//input[contains(@class,'oxd-input--active')]"
txt_email = "//label[contains(text(),'Email')]"
btn_switch = "//input[@type='checkbox']"
btn_save = "//button[@type='submit']"
btn_upload_img = "//button[@class='oxd-icon-button employee-image-action']"
btn_upload_resume = "//div[@class='oxd-file-button']"
btn_vacancy = "//div[@class='oxd-select-text-input']"
dd_vacancy_select = "//div[@role='listbox']"
date = "//div[@class='oxd-date-input']//input"
