toggle_sidebar = "//button[@class='oxd-icon-button oxd-main-menu-button']"
search = "//input[@placeholder='Search']"
btn_admin = "//li[@class='oxd-main-menu-item-wrapper'][1]"
btn_pim = "//li[@class='oxd-main-menu-item-wrapper'][2]"
btn_leave = "//li[@class='oxd-main-menu-item-wrapper'][3]"
btn_time = "//li[@class='oxd-main-menu-item-wrapper'][4]"
btn_recruitment = "//li[@class='oxd-main-menu-item-wrapper'][5]"
btn_my_info = "//li[@class='oxd-main-menu-item-wrapper'][6]"
btn_performance = "//li[@class='oxd-main-menu-item-wrapper'][7]"
btn_dashboard = "//li[@class='oxd-main-menu-item-wrapper'][8]"
btn_directory = "//li[@class='oxd-main-menu-item-wrapper'][9]"
btn_maintenance = "//li[@class='oxd-main-menu-item-wrapper'][10]"
btn_buzz = "//li[@class='oxd-main-menu-item-wrapper'][11]"
